// magicgen searches independently for NGN slider multipliers. Each candidate
// must reproduce every relevant blocker subset from the coordinate reference.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"math/bits"
	"os"
	"time"

	"github.com/ehrlich-b/ngn/internal/sliderray"
)

const defaultSeed uint64 = 0x4e474e4d41474943 // ASCII NGNMAGIC

// ngnRandom is an NGN-authored stream using the published xorshift idea. The
// fixed odd output multiplier and rotation scramble the sparse-candidate bits.
type ngnRandom struct{ state uint64 }

func (r *ngnRandom) next() uint64 {
	r.state ^= r.state << 13
	r.state ^= r.state >> 7
	r.state ^= r.state << 17
	return bits.RotateLeft64(r.state*0x4e474e52414e444f, 19) // ASCII NGNRANDO, odd
}

func find(square int, diagonal bool, random *ngnRandom) (uint64, uint64) {
	mask := sliderray.Mask(square, diagonal)
	width := bits.OnesCount64(mask)
	count := 1 << width
	occupancies := make([]uint64, count)
	attacks := make([]uint64, count)
	blockers := uint64(0)
	for i := range occupancies {
		occupancies[i] = blockers
		if diagonal {
			attacks[i] = sliderray.Bishop(square, blockers)
		} else {
			attacks[i] = sliderray.Rook(square, blockers)
		}
		blockers = (blockers - mask) & mask
	}
	stored := make([]uint64, count)
	stamp := make([]uint32, count)
	for attempt := uint32(1); attempt <= 500000000; attempt++ {
		candidate := random.next() & random.next() & random.next()
		// Low diffusion candidates rarely separate all blocker combinations.
		if bits.OnesCount64((mask*candidate)>>56) < 5 {
			continue
		}
		valid := true
		for i, occupancy := range occupancies {
			index := (occupancy * candidate) >> (64 - width)
			if stamp[index] == attempt && stored[index] != attacks[i] {
				valid = false
				break
			}
			stamp[index], stored[index] = attempt, attacks[i]
		}
		if valid {
			return candidate, uint64(attempt)
		}
	}
	panic(fmt.Sprintf("candidate budget exhausted: square=%d diagonal=%v", square, diagonal))
}

func main() {
	seed := flag.Uint64("seed", defaultSeed, "NGN PRNG seed (nonzero)")
	out := flag.String("out", "engine/slider_magics_generated.go", "generated Go source")
	flag.Parse()
	if *seed == 0 {
		panic("seed must be nonzero")
	}
	start := time.Now()
	random := ngnRandom{state: *seed}
	var body bytes.Buffer
	fmt.Fprintf(&body, "// Code generated by NGN cmd/magicgen; DO NOT EDIT.\n// Seed: 0x%016x. Sparse candidates; every blocker subset exhaustively verified.\npackage engine\n\n", *seed)
	var total uint64
	for _, diagonal := range []bool{false, true} {
		name := "rookMagicMultipliers"
		if diagonal {
			name = "bishopMagicMultipliers"
		}
		fmt.Fprintf(&body, "var %s = [64]uint64{\n", name)
		for square := 0; square < 64; square++ {
			magic, attempts := find(square, diagonal, &random)
			total += attempts
			fmt.Fprintf(&body, "0x%016x, // square %d; candidates %d\n", magic, square, attempts)
		}
		fmt.Fprintln(&body, "}")
	}
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*out, formatted, 0644); err != nil {
		panic(err)
	}
	fmt.Fprintf(os.Stderr, "NGN magics: seed=0x%016x candidates=%d elapsed=%s\n", *seed, total, time.Since(start))
}
